name: credible
description: Credible Wallet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_modular: ^3.0.0-nullsafety.41
  flutter_bloc: ^7.0.0-nullsafety.1
  bloc: ^7.0.0-nullsafety.1
  rxdart: ^0.26.0-nullsafety.1

  dio: ^3.0.10
  sembast: ^3.0.0-nullsafety.5
  sembast_web: ^2.0.0-nullsafety.1

  uuid: ^3.0.0-nullsafety.1
  flutter_svg: ^0.20.0-nullsafety.3

  google_fonts: ^1.1.2
  font_awesome_flutter: ^9.0.0-nullsafety
  cupertino_icons: ^0.1.3

  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.3.2

  path: ^1.8.0-nullsafety.3
  path_provider: ^2.0.0-nullsafety
  flutter_secure_storage: ^3.3.5

  js: ^0.6.3

  ed25519_hd_key:
    git:
      url: https://github.com/spruceid/dart-ed25519-hd-key
      ref: nullsafety

  bip39:
    git:
      url: https://github.com/spruceid/dart-bip39
      ref: nullsafety

  didkit:
    path: ../didkit/lib/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl_translation: ^0.17.10
  pedantic: ^1.10.0
  #flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/brand/logo-full.svg
    - assets/brand/logo-circular.svg
    - assets/brand/logo-title.svg
    - assets/brand/logo-subtitle.svg
    - assets/brand/logo-splash.svg
    - assets/brand/logo-minimal.svg
    - assets/brand/spruce-icon.svg
    - assets/icon/domain.svg
    - assets/icon/profile.svg
    - assets/icon/profile-filled.svg
    - assets/icon/qr-code.svg
    - assets/icon/wallet.svg
    - assets/icon/wallet-filled.svg
    - assets/icon/location-target.svg
    - assets/icon/time-clock.svg
    - assets/image/gen.svg
    - assets/image/scan.svg
