name: credible
description: Credible Wallet

publish_to: 'none'

version: 0.1.0+15

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flutter_modular: ^5.0.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  rxdart: ^0.26.0

  dio: ^4.0.6
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1

  uuid: ^3.0.6
  flutter_svg: ^1.0.3

  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.4

  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0

  path: ^1.8.0
  path_provider: ^2.0.9
  flutter_secure_storage: ^5.0.2

  js: ^0.6.3

  ed25519_hd_key: ^2.2.0
  bip39:
    git:
      url: https://github.com/spruceid/dart-bip39
      ref: fix/23/uniform-random

  didkit:
    path: ../didkit/lib/flutter

  package_info_plus: ^1.4.2
  flutter_markdown: ^0.6.9+1
  url_launcher: ^6.0.20
  logging: ^1.0.2
  shared_preferences: ^2.0.13
  local_auth: ^1.1.11
  secure_application: ^3.8.0
  provider: ^6.0.2
  dio_logging_interceptor: ^1.0.1
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.62.1
  freezed_annotation: ^2.2.0
  expandable: ^5.0.1
  flutter_json_viewer: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^7.2.4
  flutter_test:
    sdk: flutter
  #intl_translation: ^0.17.10
  freezed: ^2.3.2
  pedantic: ^1.11.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/brand/logo-full.svg
    - assets/brand/logo-circular.svg
    - assets/brand/logo-title.svg
    - assets/brand/logo-subtitle.svg
    - assets/brand/logo-splash.svg
    - assets/brand/logo-minimal.svg
    - assets/brand/spruce-icon.svg
    - assets/icon/domain.svg
    - assets/icon/profile.svg
    - assets/icon/profile-filled.svg
    - assets/icon/qr-code.svg
    - assets/icon/wallet.svg
    - assets/icon/wallet-filled.svg
    - assets/icon/location-target.svg
    - assets/icon/time-clock.svg
    - assets/image/gen.svg
    - assets/image/scan.svg
    - assets/privacy.md
    - assets/support.md
    - assets/notices.md
    - assets/terms_conditions.md
