name: credible
description: Credible Wallet

publish_to: 'none'

version: 0.1.0+15

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flutter_modular: ^3.2.0
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  rxdart: ^0.26.0

  dio: ^4.0.0
  sembast: ^3.0.2
  sembast_web: ^2.0.0

  uuid: ^3.0.4
  flutter_svg: ^0.22.0

  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  cupertino_icons: ^1.0.3

  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0

  path: ^1.8.0
  path_provider: ^2.0.1
  flutter_secure_storage: ^4.2.0

  js: ^0.6.3

  ed25519_hd_key: ^2.0.0
  bip39:
    git:
      url: https://github.com/spruceid/dart-bip39
      ref: fix/23/uniform-random

  didkit:
    path: ../didkit/lib/flutter

  package_info: ^2.0.0
  flutter_markdown: ^0.6.2
  url_launcher: ^6.0.4
  logging: ^1.0.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl_translation: ^0.17.10
  pedantic: ^1.11.0
  #flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/brand/logo-full.svg
    - assets/brand/logo-circular.svg
    - assets/brand/logo-title.svg
    - assets/brand/logo-subtitle.svg
    - assets/brand/logo-splash.svg
    - assets/brand/logo-minimal.svg
    - assets/brand/spruce-icon.svg
    - assets/icon/domain.svg
    - assets/icon/profile.svg
    - assets/icon/profile-filled.svg
    - assets/icon/qr-code.svg
    - assets/icon/wallet.svg
    - assets/icon/wallet-filled.svg
    - assets/icon/location-target.svg
    - assets/icon/time-clock.svg
    - assets/image/gen.svg
    - assets/image/scan.svg
    - assets/privacy.md
    - assets/support.md
    - assets/notices.md
    - assets/terms_conditions.md
