name: credible
description: Credible Wallet

publish_to: 'none'

version: 0.1.0+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  flutter_modular: ^5.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  rxdart: ^0.26.0

  dio: ^5.1.2
  sembast: ^3.4.5
  sembast_web: ^2.1.3

  uuid: ^3.0.6
  flutter_svg: ^2.0.7

  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.4

  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.0

  path: ^1.8.0
  path_provider: ^2.0.15
  flutter_secure_storage: ^8.0.0

  js: ^0.6.3

  ed25519_hd_key: ^2.2.0
  bip39:
    git:
      url: https://github.com/spruceid/dart-bip39
      ref: fix/23/uniform-random

  didkit:
    path: ./deps/didkit/lib/flutter

  package_info_plus: ^4.1.0
  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  local_auth: ^2.1.6
  secure_application: ^3.8.0
  provider: ^6.0.5
  fpdart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #intl_translation: ^0.17.10
  pedantic: ^1.11.1
  #flutter_launcher_icons: ^0.8.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/brand/logo-full.svg
    - assets/brand/logo-circular.svg
    - assets/brand/logo-title.svg
    - assets/brand/logo-subtitle.svg
    - assets/brand/logo-splash.svg
    - assets/brand/logo-minimal.svg
    - assets/brand/spruce-icon.svg
    - assets/icon/domain.svg
    - assets/icon/profile.svg
    - assets/icon/profile-filled.svg
    - assets/icon/qr-code.svg
    - assets/icon/wallet.svg
    - assets/icon/wallet-filled.svg
    - assets/icon/location-target.svg
    - assets/icon/time-clock.svg
    - assets/image/gen.svg
    - assets/image/scan.svg
    - assets/privacy.md
    - assets/support.md
    - assets/notices.md
    - assets/terms_conditions.md
